name: Auto Progress

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  progress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Calculate progress
        id: calc
        run: |

          make_bar () {
            percent=$1
            filled=$((percent / 5))
            empty=$((20 - filled))
            bar=$(printf "%0.s█" $(seq 1 $filled))
            space=$(printf "%0.s░" $(seq 1 $empty))
            echo "$bar$space"
          }

          calc_section () {
            start=$1
            end=$2

            section=$(awk "/$start/,/$end/" README.md)

            total=$(echo "$section" | grep -o "\- \[[ x]\]" | wc -l)
            done=$(echo "$section" | grep -o "\- \[x\]" | wc -l)

            if [ "$total" -eq 0 ]; then
              percent=0
            else
              percent=$((done * 100 / total))
            fi

            bar=$(make_bar $percent)

            echo "$done|$total|$percent|$bar"
          }

          # overall (entire README)
          total=$(grep -o "\- \[[ x]\]" README.md | wc -l)
          done=$(grep -o "\- \[x\]" README.md | wc -l)

          percent=$((done * 100 / total))
          bar=$(make_bar $percent)

          echo "OVERALL=$done|$total|$percent|$bar" >> $GITHUB_OUTPUT

          # modules
          echo "SQL=$(calc_section '<!-- SQL_START -->' '<!-- SQL_END -->')" >> $GITHUB_OUTPUT
          echo "NOSQL=$(calc_section '<!-- NOSQL_START -->' '<!-- NOSQL_END -->')" >> $GITHUB_OUTPUT
